/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HomePage;

import java.awt.print.PrinterException;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Hiep
 */
public class PrintBillFrame extends javax.swing.JFrame {
    private String customerName;
    private String customerPhone;
    private String CustomerCCCD;
    private String CheckInDate;
    private String CheckOutDate;
    private String NumberADate;
    private String Price;
    private String TotalAmount;
    private String RoomNumber;
    private String bed;
    public PrintBillFrame(String customerName) {
       initComponents();
       this.customerName = customerName;
       this.text.setText(customerName);
       getData();
        System.err.println(CustomerCCCD + " " + customerPhone + " " + CheckInDate + " " + CheckOutDate + " " + NumberADate + " " + Price + " " + TotalAmount + " "
        + RoomNumber + " " + bed);
        txtbill.setText("\t\t-: Moon Hotel :-\n");
        txtbill.setText(txtbill.getText()+"**********************************************************************************\n");
        txtbill.setText(txtbill.getText()+"Customer Details:- \n");
        txtbill.setText(txtbill.getText()+"Name:- "+this.customerName+"\n");
        txtbill.setText(txtbill.getText()+"Mobile Number:- "+customerPhone+"\n");
        txtbill.setText(txtbill.getText()+"CCCD:- "+CustomerCCCD+"\n");
        txtbill.setText(txtbill.getText()+"**********************************************************************************\n");
        txtbill.setText(txtbill.getText()+"Room Details:- \n");
        txtbill.setText(txtbill.getText()+"Room Number:- "+RoomNumber+"\n");      
        txtbill.setText(txtbill.getText()+"Bed:- "+bed+"\n");
        txtbill.setText(txtbill.getText()+"Price:- "+Price+"\n");
        txtbill.setText(txtbill.getText()+"Check IN Date="+CheckInDate+"\t\tNumber of Days="+NumberADate+"\n");
        txtbill.setText(txtbill.getText()+"Check OUT Date="+CheckOutDate+"\t\tTotal Amount="+TotalAmount+"\n");
        txtbill.setText(txtbill.getText()+"**********************************************************************************\n");
        txtbill.setText(txtbill.getText()+"\t\t"+"                    Thank You,Please Visit Again.");
        
    }
    public void getData(){
        Connection con = null;
            Statement statement = null;
            PreparedStatement pre = null;
            ResultSet rs = null;
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels","root","123456789");
                pre = con.prepareStatement("select c.phone,b.customerCCCD,c.day, c.outdate,c.date, r.price, c.amount,r.bed,r.roomnumber from bill b inner join customer c on b.customerCCCD = c.cccd inner join room r on b.roomId = r.roomnumber where name=?");
                pre.setString(1, text.getText());
                rs = pre.executeQuery();
                if(rs.next()){
                    customerPhone=rs.getString("phone");
                    CustomerCCCD=rs.getString("customerCCCD");
                    CheckInDate=String.valueOf(rs.getString("date"));
                    CheckOutDate=String.valueOf(rs.getString("outdate"));
                    NumberADate=rs.getString("day");
                    Price=rs.getString("price");
                    TotalAmount=rs.getString("amount");
                    RoomNumber=rs.getString("roomnumber");
                    bed=rs.getString("bed");
                }else{
                    JOptionPane.showMessageDialog(this, "Room number is not valid");
                }
            }catch(SQLException | ClassNotFoundException ex){} 
    }
    
    private PrintBillFrame() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/printer.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 513, -1, -1));

        txtbill.setColumns(20);
        txtbill.setRows(5);
        jScrollPane1.setViewportView(txtbill);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 495));

        text.setText("jLabel1");
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            txtbill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(PrintBillFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintBillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintBillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintBillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintBillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintBillFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel text;
    private javax.swing.JTextArea txtbill;
    // End of variables declaration//GEN-END:variables
}
