/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RoomManager;

import HomePage.manageRoomFrame;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Hiep
 */
public class testFrame extends javax.swing.JFrame {
 Connection con = null;
            Statement statement = null;
            PreparedStatement pre = null;
            ResultSet rs = null; 
    /**
     * Creates new form testFrame
     */
    public testFrame() {
        try {
            initComponents();
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels","root","123456789");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(manageRoomFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(manageRoomFrame.class.getName()).log(Level.SEVERE, null, ex);
                
            }
            showBill();
            pre = con.prepareStatement("select * from customer");
            rs = pre.executeQuery();
            ArrayList<String> li= new ArrayList<>();
            ResultSetMetaData re = rs.getMetaData();
            int c = re.getColumnCount();
            double total = 0;
            while(rs.next()){
                for(int i = 0;i<c;i++){
                    li.add(rs.getString("amount"));
            }
            }
            for (String string : li) {
                System.out.println(string);
                System.err.println(c);
            }
            System.err.println(total);
         } catch (SQLException ex) {
             Logger.getLogger(testFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
             
    }
    
    public void showBill(){
         try {
             int c = 0;
             pre=con.prepareStatement("select id, r.roomnumber, r.roomtype,c.phone, c.cccd, c.name, c.amount,c.date,c.outdate, c.day, r.price from bill b inner join customer c on b.customerCCCD = c.cccd inner join room r on b.roomId = r.roomnumber");
             rs=pre.executeQuery();
             ResultSetMetaData re = rs.getMetaData();
             c = re.getColumnCount();
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             model.setRowCount(0);
             double Total = 0;
             while(rs.next()){
                 Vector v = new Vector();
                 for(int i = 0;i<c;i++){
                     v.add(rs.getInt("id"));
                     v.add(rs.getString("name"));
                     v.add(rs.getString("cccd"));
                     v.add(rs.getString("phone"));
                     v.add(rs.getString("roomnumber"));
                     v.add(rs.getString("roomtype"));
                     v.add(rs.getString("price"));
                     v.add(String.valueOf(rs.getString("date")));
                     v.add(String.valueOf(rs.getString("outdate")));
                     v.add(rs.getString("day"));
                     v.add(rs.getString("amount"));
                     
                 }
                 model.addRow(v);
             }
             
         } catch (SQLException ex) {
             Logger.getLogger(manageRoomFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dphoneTxt = new javax.swing.JTextField();
        dClearBtn = new javax.swing.JButton();
        numberofdayTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dcccdTXt = new javax.swing.JTextField();
        dpriceTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dRoomNumberTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        totalAmountTxt = new javax.swing.JTextField();
        dnameTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dCheckInTxt = new javax.swing.JTextField();
        dCheckOutTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        crefresh_btn = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        billId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel14.setText("Price A Day");

        jLabel15.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel15.setText("Number Of Days");

        jLabel18.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel18.setText("Day Check Out");

        jButton1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/checkout.png"))); // NOI18N
        jButton1.setText("Check Out Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dphoneTxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        dphoneTxt.setEnabled(false);

        dClearBtn.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        dClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/broom.png"))); // NOI18N
        dClearBtn.setText("Clear");
        dClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dClearBtnActionPerformed(evt);
            }
        });

        numberofdayTxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel10.setText("Customer Phonenumber");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Customer phonenumber", "CCCD/CMT", "Day Check In", "Day Check Out", "Price A Day", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        dcccdTXt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        dcccdTXt.setEnabled(false);

        dpriceTxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        dpriceTxt.setEnabled(false);
        dpriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpriceTxtActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel16.setText("Total Amount");

        jLabel8.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel8.setText("Room Number");

        dRoomNumberTxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        dRoomNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dRoomNumberTxtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel12.setText("Customer Name");

        jLabel17.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel17.setText("Day Check In");

        totalAmountTxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        dnameTxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        dnameTxt.setEnabled(false);
        dnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnameTxtActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel13.setText("CCCD/CMT");

        dCheckInTxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        dCheckInTxt.setEnabled(false);

        dCheckOutTxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N

        searchBtn.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/research.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        crefresh_btn.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        crefresh_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        crefresh_btn.setText("Refresh");
        crefresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crefresh_btnActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel39.setText("Ma Hoa Don");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(79, 79, 79)
                        .addComponent(dRoomNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(crefresh_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dpriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel12)
                            .addComponent(dnameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addComponent(dCheckInTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(billId))
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberofdayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel10)
                            .addComponent(dphoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(dCheckOutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(dcccdTXt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(totalAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dRoomNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(crefresh_btn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel39)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dphoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcccdTXt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberofdayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(dnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(24, 24, 24)
                        .addComponent(dpriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jButton1)
                    .addComponent(jLabel17))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dCheckInTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dCheckOutTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(dClearBtn)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            pre = con.prepareStatement("update customer set outdate=?,amount=?,day=? where cccd=?");
            pre.setString(1, dCheckOutTxt.getText());
            pre.setString(2, totalAmountTxt.getText());
            pre.setString(3, numberofdayTxt.getText());
            pre.setString(4, dcccdTXt.getText());
            pre.executeUpdate();
            PreparedStatement pre1 = con.prepareStatement("update room set status=? where roomnumber=?");
            pre1.setString(1, "not-book");
            pre1.setString(2, dRoomNumberTxt.getText());
            pre1.executeUpdate();

            PreparedStatement pre2 = con.prepareStatement("inser into bill(id,roomId, customerCCCD) values(?,?,?)");
            pre2.setString(3, dcccdTXt.getText());
            pre2.setString(2,dRoomNumberTxt.getText());
            pre2.setString(1,billId.getText());
            pre2.executeUpdate();
        } catch (SQLException ex) {
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dClearBtnActionPerformed
        dnameTxt.setText("");
        dCheckInTxt.setText("");
        dphoneTxt.setText("");
        dCheckInTxt.setText("");
        numberofdayTxt.setText("");
        dpriceTxt.setText("");
        dRoomNumberTxt.setText("");
        totalAmountTxt.setText("");
        dcccdTXt.setText("");
    }//GEN-LAST:event_dClearBtnActionPerformed

    private void dpriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpriceTxtActionPerformed

    private void dRoomNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dRoomNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dRoomNumberTxtActionPerformed

    private void dnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnameTxtActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            pre = con.prepareStatement("select name,phone,price,cccd from customer where roomnumber=?");
            pre.setString(1, dRoomNumberTxt.getText());
            rs=pre.executeQuery();
            if(rs.next()){
                dnameTxt.setText(rs.getString("name"));
                dphoneTxt.setText(rs.getString("phone"));
                dpriceTxt.setText(rs.getString("price"));
                dcccdTXt.setText(rs.getString("cccd"));
            }
            String money="";
            PreparedStatement pre1 = con.prepareStatement("select sum(service_price) as money from oderservice o inner join service s on o.serviceOrder_id = s.service_id where booking_room=? ");
            pre1.setString(1, dRoomNumberTxt.getText());
            rs = pre1.executeQuery();
            if(rs.next()){
                money = rs.getString("money");
            }else{
                money = "0";
            }

            String s1,s2;
            s1=dCheckOutTxt.getText();
            s2=rs.getString("date");
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            Date d1 = format.parse(s1);
            Date d2 = format.parse(s2);
            long diff = d1.getTime()-d2.getTime();
            int days=(int) (diff / (24*60*60*1000));
            if(days == 0){
                days=1;
            }
            numberofdayTxt.setText(String.valueOf(days));
            double price = (Double.parseDouble(rs.getString("price")) * days) + Double.parseDouble(money);
            totalAmountTxt.setText(String.valueOf(price));
            
        } catch (SQLException ex) {
         Logger.getLogger(testFrame.class.getName()).log(Level.SEVERE, null, ex);
     } catch (ParseException ex) {
         Logger.getLogger(testFrame.class.getName()).log(Level.SEVERE, null, ex);
     }
        

    }//GEN-LAST:event_searchBtnActionPerformed

    private void crefresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crefresh_btnActionPerformed
        
    }//GEN-LAST:event_crefresh_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billId;
    private javax.swing.JButton crefresh_btn;
    private javax.swing.JTextField dCheckInTxt;
    private javax.swing.JTextField dCheckOutTxt;
    private javax.swing.JButton dClearBtn;
    private javax.swing.JTextField dRoomNumberTxt;
    private javax.swing.JTextField dcccdTXt;
    private javax.swing.JTextField dnameTxt;
    private javax.swing.JTextField dphoneTxt;
    private javax.swing.JTextField dpriceTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField numberofdayTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField totalAmountTxt;
    // End of variables declaration//GEN-END:variables
}
