/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginFrame;

import HomePage.HomeFrame;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Hiep
 */
public class CreateNewFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CreateNewFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        Back_btn = new javax.swing.JButton();
        emailTxt = new javax.swing.JTextField();
        cofimPassword_txt = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        sigIn_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Create New");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 190, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        phoneTxt.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        getContentPane().add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 220, -1));

        Back_btn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        Back_btn.setText("Back to Sigin");
        Back_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, 150, -1));

        emailTxt.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 220, -1));

        cofimPassword_txt.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        cofimPassword_txt.setEchoChar('\u0000');
        cofimPassword_txt.setFocusAccelerator('\u2022');
        getContentPane().add(cofimPassword_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 220, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel5.setText("Cofim Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        usernameTxt.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        getContentPane().add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 220, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel6.setText("Username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        passTxt.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        getContentPane().add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 220, -1));

        sigIn_btn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        sigIn_btn.setText("Sig In");
        sigIn_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sigIn_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigIn_btnActionPerformed(evt);
            }
        });
        getContentPane().add(sigIn_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/loading.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1158, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
            int n =JOptionPane.showConfirmDialog(null, "Do you want comeback to login page", "",JOptionPane.YES_NO_OPTION);
            if(n == JOptionPane.YES_OPTION){
                SigInFrame sigin = new SigInFrame();
                 this.setVisible(false);
                sigin.setVisible(true);
            }
    }//GEN-LAST:event_Back_btnActionPerformed

    private void sigIn_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigIn_btnActionPerformed
       if((usernameTxt.getText().equals("")) || (emailTxt.getText().equals("")) || (passTxt.getText().equals("")) 
                || (cofimPassword_txt.getText().equals("")) || (phoneTxt.getText().equals(""))){
            JOptionPane.showMessageDialog(this, "All field value is not null");
            usernameTxt.requestFocus();
        }else{
            Connection con = null;
            Statement statement = null;
            PreparedStatement pre = null;
            ResultSet rs = null;
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels","root","123456789");
                pre = con.prepareStatement("select * from login where email=?");
                pre.setString(1, emailTxt.getText());
                rs = pre.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Your email has been used bay another, Please try another email");
                }else{
                    if((cofimPassword_txt.getText()).equals(passTxt.getText()) ){
                        pre = con.prepareStatement("insert into login(name,email,password,phonenumber)values(?,?,?,?)");
                        pre.setString(1, usernameTxt.getText());
                        pre.setString(2, emailTxt.getText());
                        pre.setString(3, passTxt.getText());
                        pre.setString(4, phoneTxt.getText());
                        pre.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Welcome Back " + usernameTxt.getText());
                        HomePage.HomeFrame home = new HomeFrame();
                        this.setVisible(false);
                        home.setVisible(true);
                    }else{
                         JOptionPane.showMessageDialog(this, "Your password is invalid" );
                    }
                }
            }catch(SQLException | ClassNotFoundException ex){}     
        }
    }//GEN-LAST:event_sigIn_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JPasswordField cofimPassword_txt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton sigIn_btn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
