/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginFrame;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Hiep
 */
public class ForgotPasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ForgotPasswordFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        sigIn_btn = new javax.swing.JButton();
        cofimPasswordTxt = new javax.swing.JPasswordField();
        passTxt = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Forgot Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 260, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel4.setText("Cofim Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        emailTxt.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 220, -1));

        sigIn_btn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        sigIn_btn.setText("Sig In");
        sigIn_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigIn_btnActionPerformed(evt);
            }
        });
        getContentPane().add(sigIn_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, -1, -1));

        cofimPasswordTxt.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        getContentPane().add(cofimPasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 220, -1));

        passTxt.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        getContentPane().add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 220, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        back_btn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        back_btn.setText("Back to Login");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/loading.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1158, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sigIn_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigIn_btnActionPerformed
       Connection con = null;
        Statement statement = null;
        PreparedStatement pre = null;
        ResultSet rs = null;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels","root","123456789");
            pre = con.prepareStatement("select * from login where email=?");
            pre.setString(1, emailTxt.getText());
            rs = pre.executeQuery();
            if(rs.next()){
                if((cofimPasswordTxt.getText()).equals(passTxt.getText()) ){
                    pre = con.prepareStatement("update login set password=? where email=?");
                    pre.setString(1, passTxt.getText());
                    pre.setString(2, emailTxt.getText());
                    pre.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Your password is update" );
                    SigInFrame sn = new SigInFrame();
                    this.setVisible(false);
                    sn.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(this, "Your new password is invalid" );
                }

            }else{
                JOptionPane.showMessageDialog(this, "Your email is not valid");
            }
        }catch(SQLException | ClassNotFoundException ex){
            
        }
    }//GEN-LAST:event_sigIn_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        int n =JOptionPane.showConfirmDialog(null, "Do you want comeback to login page", "",JOptionPane.YES_NO_OPTION);
            if(n == JOptionPane.YES_OPTION){
                SigInFrame sigin = new SigInFrame();
                 this.setVisible(false);
                sigin.setVisible(true);
            }
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JPasswordField cofimPasswordTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JButton sigIn_btn;
    // End of variables declaration//GEN-END:variables
}
