/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginFrame;

import HomePage.HomeFrame;
import java.awt.Color;
import java.awt.Font;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Nguyen Hiep
 */
public class SigInFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public SigInFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        forgot_label = new javax.swing.JLabel();
        sigIn_btn = new javax.swing.JButton();
        sigUp_btn = new javax.swing.JButton();
        passTxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("SigIn");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 90, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        emailTxt.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        emailTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailTxtKeyTyped(evt);
            }
        });
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 220, -1));

        forgot_label.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        forgot_label.setForeground(new java.awt.Color(0, 102, 153));
        forgot_label.setText("Forgot Password ?");
        forgot_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgot_labelMouseClicked(evt);
            }
        });
        getContentPane().add(forgot_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        sigIn_btn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        sigIn_btn.setText("Sig In");
        sigIn_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigIn_btnActionPerformed(evt);
            }
        });
        getContentPane().add(sigIn_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, -1, -1));

        sigUp_btn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        sigUp_btn.setText("Sig Up");
        sigUp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigUp_btnActionPerformed(evt);
            }
        });
        getContentPane().add(sigUp_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, -1, -1));

        passTxt.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        passTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passTxtKeyTyped(evt);
            }
        });
        getContentPane().add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/loading.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1158, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgot_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_labelMouseClicked
         ForgotPasswordFrame forgot = new ForgotPasswordFrame();
         forgot.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_forgot_labelMouseClicked

    private void sigIn_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigIn_btnActionPerformed
        Connection con = null;
        Statement statement = null;
        PreparedStatement pre = null;
        ResultSet rs = null;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels","root","123456789");
            pre = con.prepareStatement("select * from login where email=? and password=?");
            pre.setString(1, emailTxt.getText());
            pre.setString(2, passTxt.getText());
            rs = pre.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "Welcome Back ");
                HomePage.HomeFrame home = new HomeFrame();
                this.setVisible(false);
                home.setVisible(true);
                
            }else{
                JOptionPane.showMessageDialog(this, "error");
            }
        }catch(SQLException | ClassNotFoundException ex){
            
        }
    }//GEN-LAST:event_sigIn_btnActionPerformed

    private void sigUp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigUp_btnActionPerformed
        CreateNewFrame createnew = new CreateNewFrame();
        this.setVisible(false);
        createnew.setVisible(true);
    }//GEN-LAST:event_sigUp_btnActionPerformed

    private void emailTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTxtKeyTyped
       
    }//GEN-LAST:event_emailTxtKeyTyped

    private void passTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTxtKeyTyped
        
    }//GEN-LAST:event_passTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SigInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SigInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SigInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SigInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SigInFrame().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel forgot_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JButton sigIn_btn;
    private javax.swing.JButton sigUp_btn;
    // End of variables declaration//GEN-END:variables
}
